# Generated by Django 3.2.6 on 2022-02-13 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 13), verbose_name='Date'),
        ),
    ]
